// <auto-generated />
namespace Task_4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_some_attribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_some_attribute));
        
        string IMigrationMetadata.Id
        {
            get { return "201702231603055_Add_some_attribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
